import {
  AimOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BankOutlined,
  BulbOutlined,
  CarOutlined,
  ClearOutlined,
  CloudOutlined,
  CoffeeOutlined,
  CompassOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DeleteOutlined,
  EnvironmentOutlined,
  ExperimentOutlined,
  FireOutlined,
  GiftOutlined,
  HeartOutlined,
  HomeOutlined,
  InsuranceOutlined,
  KeyOutlined,
  LaptopOutlined,
  MedicineBoxOutlined,
  MoonOutlined,
  PushpinOutlined,
  ReadOutlined,
  SendOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SkinOutlined,
  SmileOutlined,
  SolutionOutlined,
  SyncOutlined,
  TableOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyOutlined,
  TruckOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WifiOutlined,
} from '@ant-design/icons'
import type { ReactNode } from 'react'
import type { CategoryKey } from '../../services/expenseService/types.ts'

/** The icon of each category. Every category must have one. */
export const CATEGORY_ICONS: Record<CategoryKey, ReactNode> = {
  'entertainment.games': <AimOutlined />,
  'entertainment.movies': <VideoCameraOutlined />,
  'entertainment.music': <CustomerServiceOutlined />,
  'entertainment.sports': <TrophyOutlined />,
  'entertainment.other': <SmileOutlined />,
  'food.dining_out': <ShopOutlined />,
  'food.groceries': <ShoppingCartOutlined />,
  'food.liquor': <ExperimentOutlined />,
  'food.other': <CoffeeOutlined />,
  'home.electronics': <LaptopOutlined />,
  'home.furniture': <TableOutlined />,
  'home.supplies': <ShoppingOutlined />,
  'home.maintenance': <ToolOutlined />,
  'home.mortgage': <BankOutlined />,
  'home.pets': <HeartOutlined />,
  'home.rent': <KeyOutlined />,
  'home.services': <SolutionOutlined />,
  'home.other': <HomeOutlined />,
  'life.childcare': <SmileOutlined />,
  'life.clothing': <SkinOutlined />,
  'life.education': <ReadOutlined />,
  'life.gifts': <GiftOutlined />,
  'life.insurance': <InsuranceOutlined />,
  'life.medical': <MedicineBoxOutlined />,
  'life.taxes': <AuditOutlined />,
  'life.other': <UserOutlined />,
  'transport.bicycle': <SyncOutlined />,
  'transport.bus_train': <TruckOutlined />,
  'transport.car': <CarOutlined />,
  'transport.fuel': <DashboardOutlined />,
  'transport.hotel': <MoonOutlined />,
  'transport.parking': <PushpinOutlined />,
  'transport.plane': <SendOutlined />,
  'transport.taxi': <EnvironmentOutlined />,
  'transport.other': <CompassOutlined />,
  general: <AppstoreOutlined />,
  'utilities.cleaning': <ClearOutlined />,
  'utilities.electricity': <ThunderboltOutlined />,
  'utilities.heat_gas': <FireOutlined />,
  'utilities.trash': <DeleteOutlined />,
  'utilities.tv_phone_internet': <WifiOutlined />,
  'utilities.water': <CloudOutlined />,
  'utilities.other': <BulbOutlined />,
}
